# Generated by Django 3.1.5 on 2022-03-28 04:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('bloodgrp', models.CharField(blank=True, max_length=50, null=True)),
                ('standard', models.CharField(blank=True, choices=[('', 'Select'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100, null=True)),
                ('classs', models.CharField(blank=True, choices=[('', 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('hobby', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Dancing', 'Dancing'), ('Singing', 'Singing'), ('Playing', 'Playing')], max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
