# Generated by Django 3.1.5 on 2022-03-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.FileField(null=True, upload_to='profile/'),
        ),
    ]
